

article_list:
    path: /
    controller: App\Controller\IndexController::home

save_article:
    path: /article/save
    controller: App\Controller\IndexController::save
    methods: [POST,GET]
new_article:
    path: /article/new
    controller: App\Controller\IndexController::new
    methods: [POST,GET]
article_show:
    path: /article/{id}
    controller: App\Controller\IndexController::show
edit_article:
    path: /article/{id}
    controller: App\Controller\IndexController::edit
delete_article:
    path: /article/delete/{id}
    controller: App\Controller\IndexController::delete
    methods: [DELETE,GET]
new_category:
    path: /category/newCat
    controller: App\Controller\IndexController::delete
    methods: [POST,GET]

